batch: 16
amp: true
workers: 2
cache: disk
close_mosaic: 10
cls: 0.7
degrees: 2.0
epochs: 20
fliplr: 0.5
hsv_v: 0.4
imgsz: 832
lr0: 0.0004
lrf: 0.01
mixup: 0.0
mosaic: 0.1
optimizer: AdamW
patience: 10
scale: 0.1
translate: 0.2
